/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WsRouteImport } from './routes/ws'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerServerIdRouteImport } from './routes/server.$serverId'
import { Route as ServerServerIdIndexRouteImport } from './routes/server.$serverId.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WsRoute = WsRouteImport.update({
  id: '/ws',
  path: '/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdRoute = ServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdIndexRoute = ServerServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServerServerIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ws': typeof WsRoute
  '/server/$serverId': typeof ServerServerIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/server/$serverId/': typeof ServerServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ws': typeof WsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/server/$serverId': typeof ServerServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ws': typeof WsRoute
  '/server/$serverId': typeof ServerServerIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/server/$serverId/': typeof ServerServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/ws'
    | '/server/$serverId'
    | '/api/auth/$'
    | '/server/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/ws' | '/api/auth/$' | '/server/$serverId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/ws'
    | '/server/$serverId'
    | '/api/auth/$'
    | '/server/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  WsRoute: typeof WsRoute
  ServerServerIdRoute: typeof ServerServerIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ws': {
      id: '/ws'
      path: '/ws'
      fullPath: '/ws'
      preLoaderRoute: typeof WsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId': {
      id: '/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof ServerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId/': {
      id: '/server/$serverId/'
      path: '/'
      fullPath: '/server/$serverId/'
      preLoaderRoute: typeof ServerServerIdIndexRouteImport
      parentRoute: typeof ServerServerIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServerServerIdRouteChildren {
  ServerServerIdIndexRoute: typeof ServerServerIdIndexRoute
}

const ServerServerIdRouteChildren: ServerServerIdRouteChildren = {
  ServerServerIdIndexRoute: ServerServerIdIndexRoute,
}

const ServerServerIdRouteWithChildren = ServerServerIdRoute._addFileChildren(
  ServerServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  WsRoute: WsRoute,
  ServerServerIdRoute: ServerServerIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
